#!/bin/bash

# Variables
# NOTE: can't have all graphs in overleaf. It rejects it. Only have necessary paper graphs
SOURCE_DIR="/home/anon/paper_graphs" # Replace with the actual source directory path

./trim_graphs.py

OVERLEAF_REPO="https://git.overleaf.com/63f8de10d38edcb6d76211ec"
CLONE_DIR="/tmp/rovpp_journal_clone" # Temporary clone directory name
rm -rf "$CLONE_DIR"

# Clone the Overleaf project
git clone "$OVERLEAF_REPO" "$CLONE_DIR"

# Define the destination directory within the cloned repository
DEST_DIR="${CLONE_DIR}/figures/graphs/autogenerated"

# Clear the destination directory and copy the new content
rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
cp -R "${SOURCE_DIR}/." "$DEST_DIR"

# Navigate to the cloned Overleaf project directory
cd "$CLONE_DIR"

# Add, commit, and push changes
git add .
git commit -m "Update autogenerated graphs with directory structure"
git push

# Navigate out of the clone directory and remove it
# cd -
# rm -rf "$CLONE_DIR"
